shopping/__init__.py
# Flaskのインポート
from flask import Flask

# init_dbのインポート
from lib.db import init_db

# Flaskのアプリケーション本体を作成して、変数appに代入
app = Flask(__name__)

# 「config.py」を設定ファイルとして扱う
app.config.from_object('shopping.config')
# libフォルダ配下の「config.py」を共通設定ファイルとして扱う
app.config.from_object('lib.config')

# dbの設定
init_db(app)

# 「views.py」をインポート
from shopping.views import top, items, carts, orders

# itemアプリケーションを登録
app.register_blueprint(items.item, url_prefix='/items')
# cartアプリケーションを登録
app.register_blueprint(carts.cart, url_prefix='/carts')
# orderアプリケーションを登録
app.register_blueprint(orders.order, url_prefix='/orders')

shopping/views/carts.py
# flask関連のパッケージを取得
from flask import render_template, request, url_for, session, redirect, flash, Blueprint

# Itemモデルを取得
from lib.models import Item

# SQLAlchemyを取得
from lib.db import db

# Blueprintでcartアプリケーションを登録
cart = Blueprint('cart', __name__)

# カートを表示
@cart.route('/')
def index():
  cart = session.get('cart')
  # カートの情報を表示用に加工する
  cart_details = list()
  total_price = 0
  if type(cart) is dict:
    for item_id, item_num in cart.items():
      item = Item.query.get(int(item_id)) # 商品
      item_num = int(item_num) # 個数
      sub_total_price = item.price * item_num # 小計
      cart_details.append({'item': item, 'item_num': item_num, 'sub_total_price': sub_total_price})
      total_price += sub_total_price
  return render_template('carts/index.html', cart_details=cart_details, total_price=total_price)

# カート登録処理
@cart.route('/create', methods=['POST'])
def create():
  # 値を取得
  item_id = request.form.get('item_id') or ""
  item_num = request.form.get('item_num') or ""

  # 送信された値が数字かどうかチェック
  if not(str.isdigit(item_id) and str.isdigit(item_num)): 
    flash('数値を入力してください', 'error')
    return redirect(url_for('item.index'))

  # item_idが存在するかどうかチェック
  if Item.query.get(int(item_id)) == None:
    flash('対象の商品はありません', 'error')
    return redirect(url_for('item.index'))
  
  # cartに追加
  cart = session.get('cart')
  if type(cart) is dict:
    origin_item_num = cart.get(item_id) or 0
    cart[item_id] = origin_item_num + int(item_num)
  else:
    cart = {item_id: int(item_num)}
  session['cart'] = cart

  flash('カートに登録しました', 'success')
  return redirect(url_for('item.index'))

# カート削除処理
@cart.route('/<string:item_id>/delete', methods=['POST'])
def delete(item_id):
  if item_id == 'all':
    session.pop('cart', None)
  else:
    cart = session.get('cart')
    cart.pop(item_id, None)
    session['cart'] = cart
  flash('商品がカートから削除されました', 'success')
  return redirect(url_for('cart.index'))

shopping/views/items.py
# flask関連のパッケージを取得
from flask import render_template, request, url_for, session, redirect, flash, Blueprint

# Itemモデルを取得
from lib.models import Item, Category

# SQLAlchemyを取得
from lib.db import db

# Blueprintでitemアプリケーションを登録
item = Blueprint('item', __name__)

# 商品一覧を表示
@item.route('/')
def index():
  categories = Category.query.order_by(Category.id.desc()).all()
  items = Item.query.order_by(Item.id.desc())

  category_id = request.args.get('category_id') or ""

  if str.isdigit(category_id):
    items = items.filter(Item.category_id==category_id)
  return render_template('items/index.html', items=items, categories=categories)

shopping/views/orders.py
# flask関連のパッケージを取得
from flask import render_template, request, url_for, session, redirect, flash, Blueprint

# Itemモデルを取得
from lib.models import Order, Customer, Item

# SQLAlchemyを取得
from lib.db import db

# Blueprintでitemアプリケーションを登録
order = Blueprint('order', __name__)

# 注文フォームを表示
@order.route('/new')
def new():
  cart = session.get('cart')
  # カートの情報を表示用に加工する
  cart_details = list()
  total_price = 0
  if type(cart) is dict:
    for item_id, item_num in cart.items():
      item = Item.query.get(int(item_id)) # 商品
      item_num = int(item_num) # 個数
      sub_total_price = item.price * item_num # 小計
      cart_details.append({'item': item, 'item_num': item_num, 'sub_total_price': sub_total_price})
      total_price += sub_total_price
  return render_template('orders/new.html', cart_details=cart_details, total_price=total_price)

# 注文登録
@order.route('/create', methods=['POST'])
def create():
  # 送信情報を取得
  name = request.form.get('name')
  address = request.form.get('address')
  tel = request.form.get('tel')
  email = request.form.get('email')


  # 顧客の作成
  if name and address and tel and email:
    customer = Customer(
      name = request.form.get('name'),
      address = request.form.get('address'),
      tel = request.form.get('tel'),
      email = request.form.get('email')
    )
    db.session.add(customer)
    db.session.commit()
  else:
    flash('顧客情報を入力してください', 'error')
    return redirect(url_for('order.new'))


  # 注文の作成
  cart = session.get('cart')
  for item_id, item_num in cart.items():
    item = Item.query.get(int(item_id))
    item_num = int(item_num)
    order = Order(
      customer_id=customer.id,
      item_id=item.id,
      item_num=item_num,
      total_price=item.price * item_num
    )
    db.session.add(order)
    db.session.commit()
  session.pop('cart', None)

  flash('注文が完了しました', 'success') 
  return redirect(url_for('item.index'))

shopping/views/top.py
# flask関連のパッケージを取得
from flask import render_template, request, url_for, session, redirect, flash

# 「__init__.py」で宣言した変数appを取得
from shopping import app

# トップページを表示
@app.route('/')
def index():
  return render_template('top.html')

shopping/templates/carts/index.html
{% extends "layout.html" %}
{% block body %}
  <!-- カート -->
  <h3>
    現在のカート
    <a href="{{url_for('order.new')}}">注文確認へ</a>
  </h3>
  <table border="3">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>単価</th>
        <th>個数</th>
        <th>小計</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% if cart_details %}
        {% for cart_detail in cart_details: %}
          {% set item = cart_detail.get('item') %}
          {% set item_num = cart_detail.get('item_num') %}
          {% set sub_total_price = cart_detail.get('sub_total_price') %}
          <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.price }}円</td>
            <td>{{ item_num }}</td>
            <td>{{ sub_total_price }}円</td>
            <td>
              <form action="{{url_for('cart.delete', item_id=item.id)}}" method="POST">
                <button type="submit">削除</button>
              </form>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <td colspan="4">
          </td>
          <td>{{ total_price }}円（合計）</td>
          <td>
            <form action="{{url_for('cart.delete', item_id='all')}}" method="POST">
              <button type="submit">削除</button>
            </form>
          </td>
        </tr>
      {% endif %}
    </tbody>
  </table>
{% endblock %}

shopping/templates/items/index.html
{% extends "layout.html" %}
{% block body %}
  <!-- 商品一覧 -->
  <h3>
    商品一覧
    <a href="{{url_for('item.index')}}">すべて</a>
    {% for category in categories %}
      <a href="{{url_for('item.index', category_id=category.id)}}">{{ category.name }}</a>
    {% endfor %}
  </h3>
  <table border="3">
    <thead>
      <tr>
        <th>ID</th>
        <th>商品名</th>
        <th>分類</th>
        <th>値段</th>
        <th>カート追加</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
        <tr>
          <td><a href="{{url_for('show', id=item.id)}}">詳細</a></td>
          <td>{{ item.name }}</td>
          <td>{{ item.category.name }}</td>
          <td>{{ item.price }}円</td>
          <td>
            <form action="{{url_for('cart.create')}}" method="POST">
              <input type="hidden" value="{{ item.id }}" name="item_id">
              <input type="number" name="item_num" style="width:50px;" min="0" max="5">個
              <button type="submit">送信</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

shopping/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <h3>
      <a href="{{url_for('index')}}">TOP</a>
      <a href="{{url_for('item.index')}}">商品一覧</a>
      <a href="{{url_for('cart.index')}}">カート</a>
    </h3>
    {% for category, message in get_flashed_messages(with_categories=true) %}
      {% if category == 'success' %}
        <div style="background-color: #98fb98;">
          {{ message }}
        </div>
      {% elif category == 'error' %}
        <div style="background-color: #ffc0cb;">
          {{ message }}
        </div>
      {% endif %}
    {% endfor %}
    {% block body %}{% endblock %}
  </body>
</html>

shopping/templates/orders/new.html
{% extends "layout.html" %}
{% block body %}
  <!-- カート -->
  <h3>ご注文商品</h3>
  <table border="3">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>単価</th>
        <th>個数</th>
        <th>小計</th>
      </tr>
    </thead>
    <tbody>
      {% if cart_details %}
        {% for cart_detail in cart_details: %}
          {% set item = cart_detail.get('item') %}
          {% set item_num = cart_detail.get('item_num') %}
          {% set sub_total_price = cart_detail.get('sub_total_price') %}
          <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.price }}円</td>
            <td>{{ item_num }}</td>
            <td>{{ sub_total_price }}円</td>
          </tr>
        {% endfor %}
        <tr>
          <td colspan="4"></td>
          <td>{{ total_price }}円（合計）</td>
        </tr>
      {% endif %}
    </tbody>
  </table>

  <!-- 顧客情報入力 -->
  <h3>お客様情報を入力してください</h3>
  <form action="{{url_for('order.create')}}" method="POST">
    名前
    <div>
      <input type="text" name="name">
    </div>
    住所
    <div>
      <input type="text" name="address">
    </div>
    電話番号 
    <div>
      <input type="text" name="tel">
    </div>
    メールアドレス 
    <div>
      <input type="text" name="email">
    </div>
    <input type="submit" value="注文する">
  </form>
{% endblock %}

shopping/templates/top.html
{% extends "layout.html" %}
{% block body %}
<h3>ようこそ！サンプルショッピングサイトへ！</h3>
{% endblock %}